#!/usr/bin/env bash
# AUTO-GENERATED by scripts/provision-jira.cjs
# Run this script to set Forge environment variables for AIGO custom fields.
# Review the IDs below before running — confirm against your Jira instance.

forge variables set SEGMENT_FIELD_ID customfield_10043 --environment development
forge variables set PRIMARY_METRIC_FIELD_ID customfield_10044 --environment development
forge variables set CLAIMS_RISK_FIELD_ID customfield_10045 --environment development
forge variables set EXPERIMENT_ID_FIELD_ID customfield_10046 --environment development
forge variables set WORKFLOW_AREA_FIELD_ID customfield_10047 --environment development
forge variables set PRIORITY_SCORE_FIELD_ID customfield_10048 --environment development
